version: '3.2'
services:
  dev_server:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./openfoam_cbp/:/app/openfoam_cbp/