name: CI

on:
  push:
    branches: "**"
    tags: "v*"
  pull_request:
    branches: "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: docker build . -f test.Dockerfile -t "test/test:test"

      - name: Unit Tests
        run: docker run test/test:test
