name: CI / Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: install deps
        run: docker build . --file test.Dockerfile --tag openfoam_ci

      - name: Run tests
        run: docker run --rm -it openfoam_ci
