name: CI

on:
  push:
    branches: "main"
    tags: "v*"
  pull_request:
    branches: "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Deps Docker
        run: docker build . --target builder -t test/test:latest

      - name: Unit Tests
        run: docker run test/test:latest

      - name: Build Docker
        run: docker build . -t test/runner:latest

      - name: Run Docker
        run: docker run -d -p 3000:3000 test/runner:latest

      - name: Pull Cypress Docker
        run: docker pull cypress/included:10.0.0

      - name: E2E Tests chrome
        run: docker run --network host -v "$(pwd)"/openfoam_cbp:/tests -w /tests cypress/included:10.0.0 --browser chrome

      - name: E2E Tests firefox
        run: docker run --network host -v "$(pwd)"/openfoam_cbp:/tests -w /tests cypress/included:10.0.0 --browser firefox
